before_script:
  - git lfs pull


stages:
  - deploy


create_github_release:
    stage: deploy
    script:
        - bash ./.github/make_release.sh
#        - API_JSON=$(printf '{"tag_name":"%s",
#                              "target_commitish":"master",
#                              "name":"%s",
#                              "body":"",
#                              "draft":false,
#                              "prerelease":false}' $CI_COMMIT_TAG $CI_COMMIT_TAG)
#        - 'AUTH_HEADER="Authorization: token $GITHUB_RELEASE_TOKEN"'  # quotes avoid YAML syntax error caused by ':'
#        - curl https://api.github.com/repos/danschef/doi_testproject/releases --data "$API_JSON" -H "$AUTH_HEADER"
#        - LATEST_RELEASE=$(curl -s https://api.github.com/repos/danschef/doi_testproject/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
#        - if [ "``" != $CI_COMMIT_TAG ]; then; echo "Found a Tomcat!"; fi
#        - wget https://github.com/danschef/doi_testproject/releases/tag/$CI_COMMIT_TAG  # fails when release failed
#        - rm -rf ./$CI_COMMIT_TAG
    only:
        - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    except:
        - dev
