before_script:
  - git lfs pull


stages:
  - deploy


create_github_release:
    stage: deploy
    variables:
        GITHUB_USER: danschef
        GUTHUB_REPONAME: doi_testproject
    script:
        - bash ./.github/make_release.sh
    only:
        - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    except:
        - dev
