before_script:
  - git lfs pull


# Advise GitLab that these environment vars should be loaded from the Variables config.
variables:
    GITHUB_RELEASE_TOKEN: SECURE


stages:
  - deploy


create_github_release:
    stage: deploy
    script:
        - API_JSON=$(printf '{"tag_name":"%s",
                              "target_commitish":"master",
                              "name":"%s",
                              "body":"",
                              "draft":false,
                              "prerelease":false}' \
            $CI_COMMIT_TAG $CI_COMMIT_TAG)
        - 'AUTH_HEADER="Authorization: token $GITHUB_RELEASE_TOKEN"'  # quotes avoid YAML syntax error caused by ':'
        - echo $AUTH_HEADER
        - curl https://api.github.com/repos/danschef/doi_testproject/releases --data "$API_JSON" -H "$AUTH_HEADER"
    only:
        - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    except:
        - dev
