before_script:
  - git lfs pull


stages:
  - deploy


create_github_release:
    stage: deploy
    script:
        - bash ./.github/make_release.sh  # uses environment variables set in the UI
    only:
        - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    except:
        - dev
